version: "3.8"
name: meedz-cvblockform
services:
  web:
    build: "cvblockform/."
    ports:
      - "3000:3000"
  db:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: "cvblockform-api/."
    ports:
      - "8080:8080"
